spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName = org.postgresql.Driver
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.servlet.multipart.max-file-size = 500MB
spring.servlet.multipart.max-request-size = 500MB
spring.aws.access_key = ACCESS_KEY
spring.aws.secret_key = SECRET_KEY
spring.aws.region = ap-south-1
spring.aws.bucket_name = fhimplementbucket
spring.file.upload.path = /files
#spring.file.upload.path = /files store at system drive and spring.file.upload.path = files store at spring application's working directory